apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graphql-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: graphql-backend
        name: graphql-backend
        editor: vscode
    spec:
      containers:
        - name: graphql-backend
          image: graphql-backend:0.5
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "500m"
              memory: "100M"
            limits:
              cpu: "1000m"
              memory: "200M"
          env:
            - name: DB_CONNECTION
              value: mongodb-service
          ports:
            - containerPort: 3000
              name: express